enableGlobalCache: true

enableScripts: false

packageExtensions:
  "@storybook/addon-docs@*":
    dependencies:
      "@babel/core": "*"
      webpack: "*"
  "@storybook/docs-tools@*":
    dependencies:
      react: "*"
      react-dom: 18.0.0
  debug@*:
    dependencies:
      supports-color: "*"
  eslint-config-react-app@*:
    dependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
  flow-typed@*:
    dependencies:
      chalk: 4.1.2
  node-fetch@*:
    dependencies:
      encoding: "*"
  react-cache@*:
    dependencies:
      scheduler: "*"
  stylelint-config-recommended-scss@*:
    dependencies:
      postcss: "*"

plugins:
  - checksum: 0a2a35fbed2f33f0df1ceb1db51bf72554201f994eaecb86cbc62a295c3d05f7cc44fa8be8e64fc5e1c0bee4f529a17a0cc429ea9e3486ad467443291d5a8e3b
    path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
    spec: "https://raw.githubusercontent.com/mhassan1/yarn-plugin-after-install/v0.6.0/bundles/@yarnpkg/plugin-after-install.js"

pnpIgnorePatterns:
  - ./packages/flow-deps

yarnPath: .yarn/releases/yarn-4.5.3.cjs
