on:
  workflow_call:
    secrets:
      CHROMATIC_PROJECT_TOKEN:
        required: true

jobs:
  setenv:
    name: Set Environment Variables
    runs-on: ubuntu-latest
    outputs:
      workspaces: ${{ steps.ls_public_workspaces.outputs.workspaces }}
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: lts/*
          cache: yarn
          cache-dependency-path: ./yarn.lock
      - run: yarn install
      - id: ls_public_workspaces
        run: echo "::set-output name=workspaces::$(yarn node ./workspaces.js --ls-public)"
        shell: bash
  lint:
    name: "Lint Sources"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: lts/*
          cache: yarn
          cache-dependency-path: "**/yarn.lock"
      - run: |
          yarn install
          yarn node ./bootstrap.js
        shell: bash
      - uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4
        with:
          name: bundles_${{ github.sha }}
      - run: yarn flow-typed-install
        shell: bash
      - run: yarn flow
        shell: bash
      - run: yarn lint
        shell: bash
  test:
    name: "Test Project"
    runs-on: ubuntu-latest
    needs: setenv
    strategy:
      matrix:
        path: ${{ fromJSON(needs.setenv.outputs.workspaces).*.path }}
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: lts/*
          cache: yarn
          cache-dependency-path: "**/yarn.lock"
      - run: |
          yarn install
          yarn node ./bootstrap.js
      - run: yarn test --coverage --projects ${{ matrix.path }}
        shell: bash
      - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        with:
          name: ${{ fromJSON(needs.setenv.outputs.workspaces)[strategy.job-index].name }}_coverage_${{ github.sha }}
          path: |
            ${{ matrix.path }}/coverage
          if-no-files-found: error
          retention-days: 1
  chromatic:
    name: "Run Visual Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4
        with:
          name: bundles_${{ github.sha }}
      - uses: chromaui/action@81dfdf89d3c77ec60bf536f3e4dd86af26cf870c # v11
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: storybook-static
          onlyChanged: true
  coverage:
    name: "Report Coverage"
    runs-on: ubuntu-latest
    needs: [setenv, test]
    strategy:
      matrix:
        flag: ${{ fromJSON(needs.setenv.outputs.workspaces).*.name }}
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4
        with:
          name: ${{ matrix.flag }}_coverage_${{ github.sha }}
      - uses: codecov/codecov-action@5ecb98a3c6b747ed38dc09f787459979aebb39be # v4
        with:
          flags: ${{ matrix.flag }}
